# Generated by Django 5.1.7 on 2025-03-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0002_order_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
    ]
